.Dd 1 August 1994 (Modified 5 March 2015)
.Dt PLAYMIDI 1
.Os "Linux, OSX"
.Sh NAME
.Nm playmidi
.Nd midi file player
.Sh SYNOPSIS
.Nm playmidi
.Op Fl vblicxpVtdPeDhEzMIRCr
.Op Ar
.Sh DESCRIPTION
.Nm playmidi
is a full-featured midi file player for all systems using
sdl2.0 and later for soft synth rendering (using sf2 or math
if no sf2 file found or specified) and supports external midi output
on both Linux (via ALSA) and OSX (via CoreMidi) with more
platforms (including Windows, iOS, Android) in a future release.
When no options are specified,
.Nm playmidi
will give a summary of all command line options.
If more than one file is specified, you can use 
-r mode for interactive control, allowing
you to skip to the previous song, next song, speed up
or slow down the midi file, or repeat a midi file while viewing
a real-time display of data in the midi file.
.Sh OPTIONS
Command line options are described below.
(make sure to precede them with a dash (``-''))
.Bl -hang -width 8
.It Fl c#

set the channel mask (in hexidecimal) of which channels to
play from the midi file.   This is useful if you have a midi file
with some channels that don't sound very good on your hardware.
.It Fl d

ignore any drum (percussion) tracks in a midi file.
This is useful for non-sf2 soft synth or hardware where percussion
sounds especially bad.  Also useful for midi files where the 
percussion is poorly written.
.It Fl e

send output to external midi.   This is what you'll want to do
if you have any midi hardware connected to your system.  The
software synth is the default when this is not specified.
.It Fl E#

set mask of channels to always output to external midi.   If you want
to use more than one playback device, this option allows you to specify
what channels to send to the external midi port.  For example,
00FF would send channels 1 - 8  to external midi.  Channels not specified
in this mask will be sent to the software synth (using sf2 if available,
see -b option).
.It Fl b
filename

set filename of the sf2 file to use for soft synth renderer.
.It Fl D#

select the external device number to ouput to for 
.Fl e
or
.Fl E
options.
You can use the 
.Fl l
option to get a list of available devices.
.It Fl p[chan,]prog[,chan,prog...]

forces a given program number (1-128) to be used for all output
on given channel, or if no channel is specified, program will
be used for all channels.  For example:
.Fl p33
sets all channels to program 33, 
.Fl p5,124
sets just channel 5 to program 124, and 
.Fl p1,33,2,55,9,22,10,17
sets channel 1 to program 33, channel 2 to program 55, channel 9
to program 22, and channel 10 (percussive) to use the Power Drum Set.
.It Fl t#

skews tempo by a factor (float).   This is good for files you think
the author wrote too slow or two fast.   Also good if you want to listen
to lots of files at high-speeds, or play a file at slow speeds in order
to learn to play a song on some instrument (like piano).
.It Fl r

real time ncurses terminal playback graphics tracking of all
notes on each channel and the current playback clock.
.It Fl Px,[x]

treat channel x as percussion in soft renderer.  This
is useful if you have a file with percussion on multiple midi
channels and support for the required sysex to set it up is missing.
.It Fl R#

set initial reverb level.  Valid range is 0 - 127.
For fm, the setting is either "on" (nonzero), or "off" (zero).
.It Fl C#

set initial chorus level.  Valid range is 0 - 127.
.It Fl Vchn,vel[,chn,vel...]

set velocity for all notes in a channel.  All velocity information
for the given channel will be replaced by the given velocity.  One
day I'll change this option to allow all channels to be modified
as with the
.Fl p
option.
.It Fl x#

excludes the given channel number from the mask of channels to
load from the midi file.
.It Fl z

zero channel data in output stream -- for special applications.
.Sh AUTHOR
Nathan Laredo (laredo@gnu.org)
.Sh HISTORY
.Nm playmidi
was originally designed out of impatience with other midi
players.  The startup time on modern hardware is effectively instant.
The meaning of the various real-time displays is yet-to-be-documented.

Playmidi 2.9+ is nearly a total re-write compared with the 1995 playmidi
2.5 release.
.Sh BUGS
Currently, playmidi without the 
.Fl r
option is not supported properly. Please always use this option if you
want to hear playback.

Portamento is not yet implemented in the software synth.

Some sf2 files will render poorly in the software renderer.  It is
highly recommended you search for the file Scc1t2.sf2 via Google and
use that file with playmidi for software rendering as that was the
one used during development and works the best (and so far gives the
best soft synth experience).

This is currently
a work in progress after almost 20 years without a release, and expect
more features to come as the 3.0 release approaches.  Older features
like OPL3 FM synth and Gravis Ultrasound and AWE32 support have been
dropped in favor of the soft synth.  Ultimately, there may be soft FM
playback as well for nostalgia purposes.
If you want new features or find undocumented
ones (bugs), please email laredo@gnu.org.
